#!/bin/bash

export UVULA_REPO="$shome/git"

function get_shell_users {
  local nm_user
  for nm_user in $(getent passwd | grep ':/home' | cut -d: -f1); do 
    if [[ -d "/home/$nm_user" ]]; then 
      echo $nm_user
    fi
  done | sort

  echo root
}

function no_comments {
  grep -v '^#' || true
}

function no_blanks {
  grep -v '^[      ]*$' || true
}

function main {
  local pth_what="$1"; shift

  local pth_output="$(basename "$pth_what")"
  pth_output="$UVULA_REPO/${pth_output#what-}"

  logger_info "running $pth_what"
  what >$pth_output

  if [[ "$#" > 0 ]]; then
    exec "$shome/bin/whats" "$@"
  fi
}

require sub "$BASH_SOURCE" "$@"
