#!/bin/bash

#/ NAME
#/     collect -- run whats different and git push back to workstation
#/
#/ SYNOPSIS
#/     collect USER@localhost PORT
#/             USER: workstation login
#/             PORT: ssh remote port forward to workstation ssh

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function what {
  GIT_REPO="$1"; shift
  GIT_HOST="$1"; shift
  GIT_PORT="$1"; shift

  cd $shome
  git pull
  $shome/bin/whats "$@"
  cd $shome/git
  git remote rm origin || true
  git remote add origin "git@github.com:$GIT_REPO"
  $shome/libexec/context-git-cache "$GIT_HOST" "$GIT_PORT" git push origin master
}

require uvula "$BASH_SOURCE" "$@"
