#!/bin/bash

#/ NAME
#/     collect -- run whats different and git push back to workstation
#/
#/ SYNOPSIS
#/     collect USER@localhost PORT
#/             USER: workstation login
#/             PORT: ssh remote port forward to workstation ssh

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  logger_info "ARGS: $*"
  GIT_REPO="$1"; shift
  GIT_HOST="$1"; shift
  GIT_PORT="$1"; shift

  if [[ ! -d "$shome/git/.git" ]]; then
    mkdir -p $shome/git
    cd $shome/git
    git init
  fi

  cd $shome
  for a in "$@"; do
    env NO_LOG4SH=1 $shome/bin/whats "$a"
  done

  cd $shome/git
  git add .
  git add -u .
  git commit -m "whats $*" > /dev/null 2>&1

  git remote rm origin || true
  git remote add origin ssh://$GIT_HOST:$GIT_PORT$GIT_REPO
  
  ssh -p ${GIT_PORT} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $GIT_HOST "[[ -f $GIT_REPO/HEAD ]] || { mkdir -p $GIT_REPO; cd $GIT_REPO; git init --bare; }"
  git push origin master
}

require sub "$BASH_SOURCE" "$@"
