#!/bin/bash

#/ NAME
#/     run-collection -- collect information about a host
#/
#/ SYNOPSIS
#/     bin/run collection HOST

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# options
DEFINE_integer port "55555" "Remote port to forward to local ssh"
DEFINE_string collection "cron ifconfig mounted running rvm users stackname" "List of collectors to run"

# entry point
function main {
  local nm_host="$1"; shift

  local d='$'
  local q='"'
  exec br ssh $nm_host -- -t -A -R $FLAGS_port:localhost:22 "{ export GIT_SSH=${d}(mktemp -t XXXXXX); printf ${q}#!/bin/bash -x\\nexec ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \\${q}\\${d}@\\${q}\\n${q} > ${d}GIT_SSH; chmod 755 ${d}GIT_SSH;}; [[ -d uvula/.git ]] || git clone ssh://$LOGNAME@localhost:$FLAGS_port$shome uvula; cd uvula; git remote rm origin; git remote add origin ssh://$LOGNAME@localhost:$FLAGS_port$shome; git fetch origin; git reset --hard origin/master; bin/collect $shome/work/$nm_host $LOGNAME@localhost $FLAGS_port $FLAGS_collection; rm -f ${d}GIT_SSH"
}

require sub "$BASH_SOURCE" "$@"
