#!/bin/bash

#/ NAME
#/     whats-cron -- dump of cron jobs
#/
#/ SYNOPSIS
#/     whats-cron

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function what {
  get_shell_users
}

require uvula "$BASH_SOURCE" "$@"
