#!/bin/bash

#/ NAME
#/     whats-cron -- dump of cron jobs
#/
#/ SYNOPSIS
#/     whats-cron

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function what {
  local nm_user
  for nm_user in $(get_shell_users); do
    { sudo -u "$nm_user" crontab -l 2>&1 || true; } | no_comments | no_blanks
  done
}

require uvula "$BASH_SOURCE" "$@"
