#!/bin/bash

#/ NAME
#/     whats-running -- running processes
#/
#/ SYNOPSIS
#/     whats-running

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

function boring_processes {
  cat <<EOF
  grep sort egrep tail ps -bash cron sshd sh sleep bash CRON
EOF
}

# entry point
function what {
  ps ax -o command | tail -n +2 | grep -v '^\[' | while read -r a b; do 
    echo "$(basename -- "$a" :)= $a $b"
  done | sort -u | egrep -v "^($(boring_processes | xargs -- | sed 's# #|#g'))="
}

require uvula "$BASH_SOURCE" "$@"
