#!/bin/bash

#/ NAME
#/     whats-running -- running processes
#/
#/ SYNOPSIS
#/     whats-running

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main { 
  mkdir -p $shome/git

  $shome/bin/whats "$@"
  cd $shome/git
  git add .
  git add -u .
  git commit -m "whats $*"
  git diff 'HEAD@{1}'
  cd $shome
}

require sub "$BASH_SOURCE" "$@"
