#!/bin/bash

#/ NAME
#/     whats-TODO -- TODO
#/
#/ SYNOPSIS
#/     whats-TODO

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
}

require sub "$BASH_SOURCE" "$@"
